### ISSUE TITLE
[InventoryKeeper-2.1.0] Console show "Unknown command. Type "/help" for help." 

### ISSUE THREAD

**Issue by l3unnyAnoF4** [StarchierOrb/InventoryKeeper#4]
![image](https://user-images.githubusercontent.com/67956962/130179392-70926182-46ce-47af-80e2-fd756310318d.png)
### **Config.yml**
![image](https://user-images.githubusercontent.com/67956962/130179493-c9c0c940-8337-45bd-866e-89bfc79916c0.png)
### **items.yml**
![image](https://user-images.githubusercontent.com/67956962/130179534-6013baf2-fb57-41f4-833d-336ea314d628.png)

**Comment by l3unnyAnoF4** [comment]
I was wrong

**Comment by StarchierOrb** [comment]
Disable galacticraft mod support if not running modded server.

**Comment by l3unnyAnoF4** [comment]
fixed
